### ISSUE TITLE
Question about adj matrix

### ISSUE THREAD

**Issue by hannajiang** [ExplainableML/czsl#10]
Could you tell me what are the first few rows of the adj matrix, attributes or objects? And what's the order?

**Comment by mancinimassimiliano** [comment]
Hello @hannajiang, and sorry for the super late answer. 

In case you are still interested, the order is: attributes, then objects, and then compositions. The order is usually alphabetic (but might depend on the dataset names, as for [this function](https://github.com/ExplainableML/czsl/blob/main/data/dataset.py#L205) called [here](https://github.com/ExplainableML/czsl/blob/main/data/dataset.py#L130).
