### ISSUE TITLE
CGQA data set is not available

### ISSUE THREAD

**Issue by ans92** [ExplainableML/czsl#12]
Hi, Thank you for your work and dataset. I am trying to run the download_data.sh file. It downloads all the data sets except the cgqa. Till yesterday I can successfully download the cgqa dataset also but now it is has some issue. Can you please check it. I am getting the following error message:
```
Archive:  cgqa.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of cgqa.zip or
        cgqa.zip.zip, and cannot find cgqa.zip.ZIP, period.
```
I downloaded the cgqa.zip from the data that I downloaded through download_data.sh and found that it is not a valid file. And when I tried to download the dataset from following url it is saying that "The Connection has timed out".
https://s3.mlcloud.uni-tuebingen.de/czsl/cgqa.zip

**Comment by mancinimassimiliano** [comment]
Hello @ans92, currently we are experiencing an issue with the server hosting the dataset due to planned maintenance. I will let you know as soon as this is solved. For the dataset, please refer to the updated version, as for #3 (note that this version is hosted in the same server, thus currently unreachable).

**Comment by ans92** [comment]
Hi @mancinimassimiliano Thank you for your reply. Can you please let me know when it is expected to live again or is there any other link through which I can get the cgqa.zip file or if you can share that cgqa.zip file here if possible because all the other things are good.

**Comment by mancinimassimiliano** [comment]
Hello @ans92! The server should be back online either tomorrow or on Friday (at the latest). I will let you know as soon as the server is back online. 
p.s. In case there are further delays (very unlikely), we will look for alternative ways to share the dataset.

**Comment by ans92** [comment]
Ok. Thank you @mancinimassimiliano for your reply.

**Comment by ans92** [comment]
Hi @mancinimassimiliano , 
I also want to request can you please share a code that I can run on windows. I have tried to run the download_data.sh on windows but I got a lot of errors. Currently I am running this code on google colab but problem is it displays the output to latest 5000 lines but I want complete output. Therefore can you please share a version of your code that I can run successfully in jupyter notebook locally on windows. Thank you.

**Comment by mancinimassimiliano** [comment]
Hello @ans92! I contacted the admins and the server should be back online on Monday, unfortunately. If we have problems, we will look for alternatives to upload the dataset next week.

Regarding windows, we developed our code on linux and it is not so straightforward to port everything on Linux. We will check how to fix the notebook problem though.

**Comment by mancinimassimiliano** [comment]
Update: the server is up again, so the dataset can be downloaded. Let us know if you encounter any issues.

**Comment by ans92** [comment]
Hi @mancinimassimiliano . Thank you for this update. Yes I can now access the code. Thank you for your support.

**Comment by ans92** [comment]
Hello @mancinimassimiliano ,
I have seen you new paper 'Learning Graph Embeddings for Open World Compositional Zero-Shot Learning'. It is a very good paper and work. Have you released its code also? If yes please let me know about its link. Thank you.

**Comment by ans92** [comment]
Hi @mancinimassimiliano,
I hope you are doing well. I can see that once again the dataset is unavailable. I checked the url but there that link of cgqa dataset is not working. Can you please check the link and let me know about this issue. Thank you.
