### ISSUE TITLE
Eq. (8) in Open World Compositional Zero-Shot Learning

### ISSUE THREAD

**Issue by korcys** [ExplainableML/czsl#16]
Hi,
I noticed that there used the cosine similarity **minus** feasibility score in Eq. 8 of your paper, while it seems that the cosine similarity **plus** the feasibility score in line 236 of compcos.py.
I don't know if I'm wrong.
Thank you for your wonderful work.

**Comment by mancinimassimiliano** [comment]
Hi @korcys,

Yes, we subtract the feasibility scores, scaled by a factor \alpha in Eq. (8). Indeed in the code, we do the same:
in [this line](https://github.com/ExplainableML/czsl/blob/e467d248342edd183f4d5ea73b456a2c9f02607d/models/compcos.py#L237) we add the `feasibility_margin` to the unseen compositions. The unseen margins are computed as a scaled version of the feasibility scores (see [this line](https://github.com/ExplainableML/czsl/blob/e467d248342edd183f4d5ea73b456a2c9f02607d/models/compcos.py#L192)), where the scale is defined by `self.cosine_margin_factor`.

Now,  `self.cosine_margin_factor` (defined [here](https://github.com/ExplainableML/czsl/blob/e467d248342edd183f4d5ea73b456a2c9f02607d/models/compcos.py#L69)) is a negative value (i.e. -\alpha), thus the feasibility margins are nothing else than _-\alpha*feasibility_scores_ (i.e. as in Eq. (8) of the paper).

Indeed, our choice of names for the variables is a bit unclear and I apologize for that. I hope to have clarified your doubts nevertheless.

**Comment by korcys** [comment]
Thank you for your nice and quick reply.
