### ISSUE TITLE
Questions about datasets

### ISSUE THREAD

**Issue by jiayaohua** [ExplainableML/czsl#18]
What do the numbers in the names of the images in the dataset mean?for example： 1-2-orange-shirt.jpg

**Comment by ferjad** [comment]
It has been a while since I created the dataset but I think one of those numbers was the image index in the gqa dataset and the other was the filtered bounding box used to crop within that image followed by the state and the object.

**Comment by jiayaohua** [comment]
If I'm going to build my own dataset, do I have to have the preceding numeric index?

**Comment by ferjad** [comment]
Have a look at the dataset class, we define the dataset image paths and labels in a t7 file, so you dont necessarily have to contain the same numeric indexes. Just make sure your t7 file is correctly pointing to your new dataset.

**Comment by jiayaohua** [comment]
Thank you very much for your answers
