### ISSUE TITLE
dataset.py  role + metadata_compositional-split-natural.t7 structure

### ISSUE THREAD

**Issue by jiayaohua** [ExplainableML/czsl#19]
What is the role of dateset.py?And how is metadata_compositional-split-natural.t7 made?

**Comment by mancinimassimiliano** [comment]
Hi @jiayaohua,

`dataset.py` splits the data into training, validation, and test set, processing the input split to get attributes, objects, and compositional information. 

`metadata_compositional-split-natural.t7` is a list of dictionaries, where each dictionary contains four keys:
- _image_: with the image path
- _attr_: with attribute label
- _obj_: with object label
- _set_: with the set (training, validation, test) to which the image belongs.
