### ISSUE TITLE
ValueError: Harmonic mean only defined if all elements greater than zero

### ISSUE THREAD

**Issue by jiayaohua** [ExplainableML/czsl#22]
in common.py 489line
unseen_match the first element is 0 causes subsequent calculations of hm to be incorrect

**Comment by mancinimassimiliano** [comment]
Hello @jiayaohua! Yes, indeed if unseen_match is zero, the harmonic mean computed for the first element would be not determined. However, we used this implementation of the harmonic mean [from scipy](https://github.com/scipy/scipy/blob/v1.9.0/scipy/stats/_stats_py.py#L315-L407) that tackles this issue by setting to 0 the HM if one of the two inputs is zero. 

This is consistent with previous works (e.g. in [CZSL](https://github.com/nv-research-israel/causal_comp/blob/7b26f00bd7b28d0e4cb80147e2ce302ead5cde75/eval.py#L214) and [GZSL](https://github.com/wenjiaXu/APN-ZSL/blob/master/model/main.py#L202-L206)) and comes from the rationale that the HM in this context is measuring a tradeoff between two accuracies (i.e. seen/unseen): if one is zero, the tradeoff is not existent, thus we achieve the lowest possible value of the score (i.e. zero). 

Finally, note that zero values do not affect the final computation of the HM: if for at least one bias value both unseen and seen accuracies are greater than zero, the [output HM](https://github.com/ExplainableML/czsl/blob/main/models/common.py#L502) will be correctly computed and different from zero (as it is for all values we achieved, also when reproducing previous works).
