### ISSUE TITLE
Qualitative results.

### ISSUE THREAD

**Issue by jiayaohua** [ExplainableML/czsl#24]
How do you check the qualitative results in your paper?

**Comment by mancinimassimiliano** [comment]
Hello @jiayaohua and sorry for the very late reply! 

If you want to check qualitatives, you should like predictions of the model to the actual images in the datasets. You can do it by enabling `return_images=True` (see [this](https://github.com/ExplainableML/czsl/blob/main/data/dataset.py#L115)) while creating the dataset (e.g. [here](https://github.com/ExplainableML/czsl/blob/main/test.py#L62)). The image path will then be added at the end of your `data` list, and you can use `data[-1]` to check the path (see [here](https://github.com/ExplainableML/czsl/blob/main/data/dataset.py#L433) even if for now it is implemented only for val/test splits). 

Hope the answer is still useful, but please feel free to ask questions in case of doubts.
