### ISSUE TITLE
Download link Broken

### ISSUE THREAD

**Issue by mxjmxj1** [ExplainableML/czsl#25]
download_data.sh
wget --show-progress -O $FOLDER/splits.tar.gz https://www.senthilpurushwalkam.com/publication/compositional/compositional_split_natural.tar.gz
leads to a blank page. Any help would be greatly appreciated.

**Comment by wqshmzh** [comment]
> 

Here: https://www.senthilpurushwalkam.com/publication/compositional/compositional_split_natural.tar.gz

**Comment by mancinimassimiliano** [comment]
Thank you very much @mxjmxj1 and @wqshmzh for spotting and fixing this! 
I have uploaded the download script with the new link.
