### ISSUE TITLE
Missing multi-GPU option

### ISSUE THREAD

**Issue by Harzva** [ExplainableML/czsl#33]
I found that this task  does not use multiple gpu training ，why? thank you very much.

**Comment by mancinimassimiliano** [comment]
hi @Harzva! We did not focus on multi-GPU as usually the training is very lightweight and we saw a single GPU (with even less than 4GB of RAM for smaller datasets) to suffice. Problems can rise only for C-GQA, but as far as I remember, experiments were fitting on a single GPU with 8/12GB.  

In case you are experiencing issues, you can also consider using other repos we produced (e.g. [Co-CGE](https://github.com/ExplainableML/co-cge), [KG-SP](https://github.com/ExplainableML/KG-SP) which contain a flag for a faster evaluation.

I hope this helps anyway.
