### ISSUE TITLE
C-GQA dataset validation split stats on Co-CGE: seen and unseen switched

### ISSUE THREAD

**Issue by WangZN11** [ExplainableML/czsl#36]
While consolidating and deduplicating dataset labels, I discovered some numerical issues. The problem arises in the Validation column of the statistical data for C-GQA in Table 1 of the Co-CGE paper. I would like to request the authors to confirm whether the positions of sp and up, i.e., seen and unseen, are mistakenly switched in this column.

**Comment by mancinimassimiliano** [comment]
Hi @WangZN11,
Indeed you are right and the two numbers are switched by mistake. Thank you for spotting this!
