### ISSUE TITLE
Code for generating adjacency matrix.

### ISSUE THREAD

**Issue by MuchHair** [ExplainableML/czsl#5]
Hi! Thanks for your excellent work. 
I tried to generate adjacency matrix for the graph model according to your paper. But I found there are some differences between my version and your given. Would you mind sharing the code for generating adjacency matrix ?
Thanks a lot!

**Comment by MuchHair** [comment]
Specially, I found edges between some states are set to 1, e.g. `ancient' and `modern'. Why for these settings?

**Comment by mancinimassimiliano** [comment]
Hi @MuchHair! Sorry for the huge delay in answering this issue. I updated the code to solve another issue and, in the process, I added the snippet to generate the adjacency matrix/graph on the fly, depending on the input. In case you are still interested (I do not blame you if you are not, we took too long to answer), you can check the relevant part out here: https://github.com/ExplainableML/czsl/blob/main/models/graph_method.py#L109.
