### ISSUE TITLE
Question about train_forward_bce function in ManifoldModel

### ISSUE THREAD

**Issue by bighuang624** [ExplainableML/czsl#6]
Hi,

Thanks for the high quality open-resourced codebase.

I suspect that the Line 59 of `czsl/models/manifold_methods.py` should be

```py
composed_clf = self.compose(sampled_attrs, sampled_objs)
```

instead of the current

```py
composed_clf = self.compose(attrs, objs)
```

As I am a beginner in the CZSL field, I apologize for any misunderstandings that may exist. Looking forward to any response.

**Comment by mancinimassimiliano** [comment]
Hi @bighuang624, 

You are right, thanks for spotting that out. That part has been taken from [this repo](https://github.com/Tushar-N/attributes-as-operators/blob/master/models/models.py) and affects only RedWine that has not been included as baselines in the experiments. We will fix it.

**Comment by mancinimassimiliano** [comment]
Fixed together with the embedding init strategy. I am closing this, thanks again @bighuang624!
